"""Add AudioGeneration table

Revision ID: 98e8c8864842
Revises: b840913f16ab
Create Date: 2026-09-18 21:24:00.566241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98e8c8864842'
down_revision = 'b840913f16ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audio_generations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=50), nullable=False),
    sa.Column('voice', sa.String(length=50), nullable=False),
    sa.Column('audio_storage_reference', sa.String(length=500), nullable=False),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audio_generations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audio_generations_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audio_generations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audio_generations_user_id'))

    op.drop_table('audio_generations')
    # ### end Alembic commands ###
