"""Add timeline metadata

Revision ID: eb23467b6c8e
Revises: 98e8c8864842
Create Date: 2026-09-21 16:53:17.504187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb23467b6c8e'
down_revision = '98e8c8864842'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audio_generations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('listening_data', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audio_generations', schema=None) as batch_op:
        batch_op.drop_column('listening_data')

    # ### end Alembic commands ###
